[tool.poetry]
name = "gemini-functions-agent"
version = "0.1.0"
description = "Agent using Gemini function calling to execute functions, including search"
authors = [
    "Harrison Chase",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
langchain-google-vertexai = "^0.0.3"
tavily-python = "^0.1.9"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "gemini_functions_agent"
export_attr = "agent_executor"

[tool.templates-hub]
use-case = "research"
author = "LangChain"
integrations = ["Google", "Tavily"]
tags = ["search", "agents", "function-calling"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
