name: "\U0001F680 Запрос на функциональность"
description: Отправьте запрос или сделайте предложение по доработке функциональности GigaChain
labels: ["02 "]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checked
      description: Please confirm and check all the following options.
      options:
        - label: I searched existing ideas and did not find a similar one
          required: true
        - label: I added a very descriptive title
          required: true
        - label: I've clearly described the feature request and motivation for it
          required: true
  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
      label: Описание функциональности
      description: |
        Краткое описание предлагаемых доработок по существу. Приведите ссылки на подходящие GitHub-репозитории, статьи или другие ресурсы.

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Обоснование
      description: |
        Опишите, что побудило вас предложить доработку. Если предложенная функциональность связанна с существующей issue, дайте ссылку на неё.

  - type: textarea
    id: proposal
    validations:
      required: false
    attributes:
      label: Ваш вклад
      description: |
        Возможно, вы хотите предложить свое решение и отправить PR? Пожалуйста, ознакомьтесь с правилами создания PR, описанными в [CONTRIBUTING.MD](https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md).
