name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve LangChain. To report a security issue, please instead use the security option below.
labels: ["02 Bug Report"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. Before creating a new
        issue, please make sure to take a few moments to check the issue tracker
        for existing issues about the bug.

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces issue. 
        It can be a Colab link or just a code snippet. The snippet should be *minimal* and *self-contained*. It should include *all* relevant imports and data definitions.
        
        Please include a **full** stack trace (i.e., the error message and the entire log) unless you KNOW that the stack trace is not relevant.
        
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        
        The following code: 
        
        ```python
        
        from langchain import ....
        # Some code goes here
        ```
        
        Here is the full stack trace:

  - type: textarea
    id: expected-behavior
    validations:
      required: false
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."

  - type: checkboxes
    id: related-components
    attributes:
      label: Related Components
      description: "Select the components related to the issue (if applicable):"
      options:
        - label: "LLMs/Chat Models"
        - label: "Embedding Models"
        - label: "Prompts / Prompt Templates / Prompt Selectors"
        - label: "Output Parsers"
        - label: "Document Loaders"
        - label: "Vector Stores / Retrievers"
        - label: "Memory"
        - label: "Agents / Agent Executors"
        - label: "Tools / Toolkits"
        - label: "Chains"
        - label: "Callbacks/Tracing"
        - label: "Async"

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system info with us.
      placeholder: LangChain version, platform, python version, ...
    validations:
      required: true

