name: Документация
description: Расскажите как мы можем улучшить документацию GigaChain.
title: "DOC: <Укажите развернутый заголовок после префикса 'DOC: '>"
labels: [03 - Документация]

body:
- type: markdown
  attributes:
    value: >
      Thank you for taking the time to report an issue in the documentation.
      
      Only report issues with documentation here, explain if there are
      any missing topics or if you found a mistake in the documentation.
      
      Do **NOT** use this to ask usage questions or reporting issues with your code.
      
      If you have usage questions or need help solving some problem, 
      please use [GitHub Discussions](https://github.com/langchain-ai/langchain/discussions).
      
      If you're in the wrong place, here are some helpful links to find a better
      place to ask your question:
      
      [LangChain documentation with the integrated search](https://python.langchain.com/docs/get_started/introduction),
      [API Reference](https://api.python.langchain.com/en/stable/),
      [GitHub search](https://github.com/langchain-ai/langchain),
      [LangChain Github Discussions](https://github.com/langchain-ai/langchain/discussions),
      [LangChain Github Issues](https://github.com/langchain-ai/langchain/issues?q=is%3Aissue),
      [LangChain ChatBot](https://chat.langchain.com/)
- type: checkboxes
  id: checks
  attributes:
    label: Checklist
    description: Please confirm and check all the following options.
    options:
      - label: I added a very descriptive title to this issue.
        required: true
      - label: I included a link to the documentation page I am referring to (if applicable).
        required: true
- type: textarea
  attributes: 
    label: "Проблема с существующей документацией:"
    description: >
      Оставьте ссылку на страницу документации или файл кода, где, по вашему мнению, нужно доработать документацию.

- type: textarea
  attributes:
    label: "Запрос на доработку:"
    description: >
      По возможности подробнее опишите какие темы следует отразить в существующей документации, по вашему мнению.