name: Другое
description: Предложите обсудить проблему, которая не попадает в другие категории.
title: "Issue: <Укажите развернутый заголовок после префикса 'Issue: ' prefix>"
labels: [04 - Другое]

body:
  - type: textarea
    attributes:
      label: "Проблема, которую вы хотите обсудить."
      description: >
        Как можно подробнее опишите проблему, которую вы хотите обсудить.
        Приведите ссылки на подходящие ресурсы.

  - type: textarea
    attributes:
      label: "Предложение:"
      description: >
        Опишите, как вы видите решение проблемы.
