[tool.poetry]
name = "plate-chain"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
gigachain = ">=0.0.325"
openai = "^0.28.1"
gigaserve = "^0.0.19"

[tool.poetry.group.dev.dependencies]
gigachain-cli = ">=0.0.4"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.gigaserve]
export_module = "plate_chain"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
