[tool.poetry]
name = "rag-astra"
version = "0.1.0"
description = ""
authors = ["Stefano Lottini <stefano.lottini@datastax.com>",
           "Eric Hare <eric.hare@datastax.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.313, <0.1"
openai = ">=0.28.1"
tiktoken = ">=0.5.1"
cassio = ">=0.1.3"

[tool.langserve]
export_module = "rag_astra"
export_attr = "chain"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
