[tool.poetry]
name = "rag-clickhouse"
version = "0.1.0"
description = "RAG using local LLM, embeddings, vectorstore"
authors = [
    "Mark Needham <mark.needham@clickhouse.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
tiktoken = ">=0.5.1"
clickhouse-connect = ">=0.7.0"
gpt4all = ">=1.0.8"
beautifulsoup4 = ">=4.12.2"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_clickhouse"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "ClickHouse", "Gpt4all", "Ollama"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
