[tool.poetry]
name = "langgraph-retrieval-agent-fireworks"
version = "0.0.1"
description = "Retrieval agent for open source models hosted on Fireworks"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0,<4.0"
langchain = "^0.1"
langgraph = "^0.0.30"
langchainhub = "^0.1.15"
langchain-fireworks = "^0.1.1"
langchain-community = "^0.0.29"
arxiv = "^2.1.0"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "langgraph_retrieval_agent_fireworks"
export_attr = "agent_executor"

[tool.templates-hub]
use-case = "research"
author = "Docugami"
integrations = ["HuggingFace"]
tags = ["local", "agents"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
