[tool.poetry]
name = "rag-lancedb"
version = "0.0.1"
description = "lancedb as vectordb integration"
authors = [ "akash desai  <aksdesai1998@gmail.com>",]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.325"
lancedb = ">=0.3.3"
openai = ">=0.28.1"
tiktoken = ">=0.5.1"



[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "rag_lancedb"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
