---
name: Imports

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run import check
      run: |
        # We should not encourage imports directly from main init file
        # Expect for __version__ and hub
        # And of course expect for this file
        git grep 'from langchain import' | grep -vE 'from langchain import (__version__|hub)' | grep -v '.github/workflows/check-imports.yml' && exit 1 || exit 0
        
        # Now let's start to check the langchain package itself
        cd libs/langchain
        
        # Pydantic bridge should not import from any other module
        git grep 'from langchain' langchain/pydantic_v1 && exit 1 || exit 0
        
        # load should not import from anything except itself and pydantic_v1
        git grep 'from langchain' langchain/load | grep -vE 'from langchain.(pydantic_v1|load)' && exit 1 || exit 0
        
        # utils should not import from anything except itself and pydantic_v1
        git grep 'from langchain' langchain/utils | grep -vE 'from langchain.(pydantic_v1|load|utils)' && exit 1 || exit 0
