name: CI

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: armand-sauzay/actions-python/lint@v1
        with:
          python-version: ${{ matrix.python-version }}

  test:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: armand-sauzay/actions-python/test@v1
        with:
          python-version: ${{ matrix.python-version }}
          test-flags: "tests/unit_tests"
