name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: armand-sauzay/actions-python/lint@v1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: armand-sauzay/actions-python/test@v1

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: armand-sauzay/actions-python/release@v1
