name: Scheduled tests

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI
  schedule:
    - cron:  '0 13 * * *'

env:
  POETRY_VERSION: "1.7.1"

jobs:
  integration_test_openai:
    uses: ./.github/workflows/_integration_test.yml
    with:
      working-directory: "libs/partners/openai"

  integration_test_anthropic:
    uses: ./.github/workflows/_integration_test.yml
    with:
      working-directory: "libs/partners/anthropic"
