name: test

on:
  push:
    branches: [master]
  pull_request:

env:
  POETRY_VERSION: "1.4.2"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        test_type:
          - "core"
          - "extended"
    name: Python ${{ matrix.python-version }} ${{ matrix.test_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
